version: "3.8"
services:
  certbot-service:
    image: latera/certbot-service
    container_name: certbot-service
    restart: unless-stopped
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    env_file: .env
volumes:
  certbot-etc:
  certbot-var:
